FROM ruby:3.3.9 AS builder

RUN apt-get update && apt-get install -y --no-install-recommends build-essential
RUN apt-get install -y curl bash
RUN apt-get install -y postgresql-client
RUN apt-get install -y libpq-dev

WORKDIR /app

COPY Gemfile* ./

RUN bundle install

FROM ruby:3.3.9

RUN apt-get update && apt-get install -y --no-install-recommends build-essential
RUN apt-get install -y curl bash
RUN apt-get install -y postgresql-client
RUN apt-get install -y libpq-dev

WORKDIR /app

COPY --from=builder /usr/local/bundle/ /usr/local/bundle/

COPY . .

RUN rm -rf storage/* .env tmp/cache log/*

COPY docker/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

CMD ["/bin/bash", "-c", "entrypoint.sh && rm -f tmp/pids/server.pid && rails db:migrate && rails server -b 0.0.0.0"]
